name: Build Dashboard

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        path: './'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Dashboard'
          output:
            format: markdown
            filename: 'README.md'
          sections:
          - title: 'Issues'
            widgets:
            - type: 'table'
              title: 'New Pull Requests (This Week)'
              issue_query: 'repo:Pixie-Axerup/issue-pr-table is:open is:issue'
        token: ${{ github.token }}

    - name: Publish Documentation
      run: |
        git add .
        git config --global user.email "pixie.axerup@ingka.ikea.com"
        git config --global user.name "Pixie Axerup"
        git commit -m 'Documentation update' --allow-empty
        git push origin main
      working-directory: ./
