name: Build Dashboard

on:
  workflow_dispatch:
  schedule:
  - cron: 0 * * * *

permissions:
  contents: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        path: './'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Welcom to Observability Pipeline team'
          output:
            format: markdown
            filename: 'README.md'
          sections:
          - title: 'About'
            description: team members - [Pixie](https://github.com/Pixie-Axerup), [Timothy](https://github.com/timothy-mahoney)
            widgets:
            - type: 'table'
              title: 'Our repositories'
              headers:
              - 'Project'
              - 'Description'
              - 'Open Issues'
              - 'Open PRs'
              elements:
              - - value: 'Issue-pr-table'
                  url: 'https://github.com/Pixie-Axerup/issue-pr-table'
                - value: 'This is my test repo'
                - script: |
                    const repo = 'Pixie-Axerup/issue-pr-table'
                    const results = await github.search.issuesAndPullRequests({
                      q: `repo:${repo} is:issue is:open}`
                    })
                    const count = results.data.total_count
                    const title = 'Open issues'
                    const color = (count > 10) ? 'red' : 'green'
                    return { value: count, title: title, color: color }
                - script: |
                    const repo = 'Pixie-Axerup/issue-pr-table'
                    const results = await github.search.issuesAndPullRequests({
                      q: `repo:${repo} is:pr is:open}`
                    })
                    const count = results.data.total_count
                    const title = 'Open PRs'
                    const color = (count > 5) ? 'red' : 'green'
                    return { value: count, title: title, color: color }
        token: ${{ github.token }}

    - name: Publish Documentation
      run: |
        git add .
        git config --global user.email "pixie.axerup@ingka.ikea.com"
        git config --global user.name "Pixie Axerup"
        git commit -m 'Documentation update' --allow-empty
        git push origin main
      working-directory: ./
